create table "ORDER" (
    ID integer generated by default as identity,
    ITEM varchar(255),
    PRICE integer,
    CONTACT varchar(255),
    STATUS varchar(255),
    NOTE varchar(255),
    constraint "ORDER"_PK primary key(ID)
);
