create table "ORDER" (
    ID integer generated by default as identity,
    ITEM varchar(255),
    PRICE integer,
    CONTACT varchar(255),
    STATUS varchar(255),
    NOTE varchar(255)
);

insert into "ORDER" values (1, "商品１", "3000", "山田", "0", "特になし");

